export type Person = string
export type PersonProfile = { id: string; name: string; color: string }
export type PersonSet = { id: string; reps: string; weight: string }
export type ExerciseSetsByPerson = Record<string, PersonSet[]>
export type ExerciseTemplate = { id: string; name: string; enabledByDefault: boolean; order: number; createdAt: string; updatedAt: string }
export type WorkoutExercise = { id: string; exerciseTemplateId: string | null; name: string; order: number; setsByPerson: ExerciseSetsByPerson; isCompleted?: boolean }
export type Workout = { id: string; date: string; people: PersonProfile[]; exercises: WorkoutExercise[]; createdAt: string; updatedAt: string }
export type AppState = { version: 3; people: PersonProfile[]; exerciseTemplates: ExerciseTemplate[]; workouts: Workout[]; activeWorkoutId: string | null }
export type WorkoutCreationMode = 'withTemplates' | 'empty'
