import { describe, expect, it } from 'vitest'
import { createInitialState } from '../storage/appStorage'
import { appReducer } from './appReducer'

const withWorkout = () => appReducer(createInitialState(), { type: 'CREATE_WORKOUT', now: new Date(2026, 6, 14) })

describe('appReducer', () => {
  it('vytvoří a otevře nový trénink', () => { const state = withWorkout(); expect(state.workouts).toHaveLength(1); expect(state.activeWorkoutId).toBe(state.workouts[0].id) })
  it('otevře uložený trénink', () => { let state = withWorkout(); const id = state.workouts[0].id; state = appReducer(state, { type: 'CLOSE_WORKOUT' }); expect(appReducer(state, { type: 'OPEN_WORKOUT', id }).activeWorkoutId).toBe(id) })
  it('odstraní celý trénink', () => { const state = withWorkout(); expect(appReducer(state, { type: 'DELETE_WORKOUT', id: state.workouts[0].id }).workouts).toHaveLength(0) })
  it('uloží odlišné hodnoty Lukáše a Terky', () => { let state = withWorkout(); const workout = state.workouts[0], exercise = workout.exercises[0], set = exercise.sets[0]; state = appReducer(state, { type: 'UPDATE_SET', workoutId: workout.id, exerciseId: exercise.id, setId: set.id, person: 'lukas', field: 'weight', value: '100,5' }); state = appReducer(state, { type: 'UPDATE_SET', workoutId: workout.id, exerciseId: exercise.id, setId: set.id, person: 'terka', field: 'reps', value: '12' }); expect(state.workouts[0].exercises[0].sets[0].lukas.weight).toBe('100,5'); expect(state.workouts[0].exercises[0].sets[0].terka.reps).toBe('12') })
  it('přidá další prázdnou sérii', () => { const state = withWorkout(), workout = state.workouts[0], exercise = workout.exercises[0]; const next = appReducer(state, { type: 'ADD_SET', workoutId: workout.id, exerciseId: exercise.id }); expect(next.workouts[0].exercises[0].sets).toHaveLength(2); expect(next.workouts[0].exercises[0].sets[1].lukas.reps).toBe('') })
  it('odstraní sérii, pokud jich je více', () => { let state = withWorkout(); const workout = state.workouts[0], exercise = workout.exercises[0]; state = appReducer(state, { type: 'ADD_SET', workoutId: workout.id, exerciseId: exercise.id }); const setId = state.workouts[0].exercises[0].sets[1].id; expect(appReducer(state, { type: 'REMOVE_SET', workoutId: workout.id, exerciseId: exercise.id, setId }).workouts[0].exercises[0].sets).toHaveLength(1) })
  it('neodstraní poslední sérii', () => { const state = withWorkout(), workout = state.workouts[0], exercise = workout.exercises[0]; const next = appReducer(state, { type: 'REMOVE_SET', workoutId: workout.id, exerciseId: exercise.id, setId: exercise.sets[0].id }); expect(next.workouts[0].exercises[0].sets).toHaveLength(1) })
  it('přidá vlastní cvik jen do tréninku', () => { const state = withWorkout(), count = state.exerciseTemplates.length, workout = state.workouts[0]; const next = appReducer(state, { type: 'ADD_EXERCISE', workoutId: workout.id, name: '  Hip thrust ', addToTemplates: false }); expect(next.workouts[0].exercises.at(-1)?.name).toBe('Hip thrust'); expect(next.exerciseTemplates).toHaveLength(count) })
  it('přidá vlastní cvik také mezi šablony', () => { const state = withWorkout(), workout = state.workouts[0]; const next = appReducer(state, { type: 'ADD_EXERCISE', workoutId: workout.id, name: 'Hip thrust', addToTemplates: true }); expect(next.exerciseTemplates.some((item) => item.name === 'Hip thrust')).toBe(true) })
  it('nevytvoří duplicitní šablonu kvůli mezerám nebo velikosti písmen', () => { const state = withWorkout(), workout = state.workouts[0], count = state.exerciseTemplates.length; const next = appReducer(state, { type: 'ADD_EXERCISE', workoutId: workout.id, name: '  LEG   PRESS ', addToTemplates: true }); expect(next.exerciseTemplates).toHaveLength(count) })
  it('deaktivuje šablonu a další trénink ji nepřevezme', () => { let state = createInitialState(); const template = state.exerciseTemplates[0]; state = appReducer(state, { type: 'TOGGLE_TEMPLATE', id: template.id }); state = appReducer(state, { type: 'CREATE_WORKOUT' }); expect(state.workouts[0].exercises.some((item) => item.name === template.name)).toBe(false) })
  it('odstranění šablony nemaže cvik ze staršího tréninku', () => { let state = withWorkout(); const template = state.exerciseTemplates[0]; state = appReducer(state, { type: 'DELETE_TEMPLATE', id: template.id }); expect(state.workouts[0].exercises.some((item) => item.name === template.name)).toBe(true) })
  it('přejmenování šablony nepřejmenuje starší cvik', () => { let state = withWorkout(); const template = state.exerciseTemplates[0]; state = appReducer(state, { type: 'RENAME_TEMPLATE', id: template.id, name: 'Nový název' }); expect(state.workouts[0].exercises[0].name).toBe('Leg press'); expect(state.exerciseTemplates[0].name).toBe('Nový název') })
  it('mění pořadí šablon', () => { const state = createInitialState(), second = state.exerciseTemplates[1]; const next = appReducer(state, { type: 'MOVE_TEMPLATE', id: second.id, direction: -1 }); expect([...next.exerciseTemplates].sort((a, b) => a.order - b.order)[0].id).toBe(second.id) })
})
